apiVersion: app/v1
kind: deployment
metadata: 
  name: vpromemcache
  labels:
   app: vprmemcache

spec: 
  replicas: 1
  selector:
    matchlabel:
     app: vprmemcache

  template:
   metadata:
     labels: 
       app: vprmemcache

    spec: 
      container: 
       - name: vpromemcache
         image: -----------
         ports:
         - name: memcache-port
           containerPort: 11211
